services:
    mailpit:
        container_name: kn-mailpit
        image: axllent/mailpit
        volumes:
            -   kn_mailpit_data:/data
        ports:
            -   8025:8025 #UI mailpit port
            -   1025:1025 #SMTP port
        networks:
            - knowy_net
        environment:
            MP_MAX_MESSAGES: 1000
            MP_DATABASE: /data/knmailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
    kn_mailpit_data:

networks:
    knowy_net: