services:
    web-server:
        build: server
        container_name: kn-server
        ports:
            - "8080:8080"
        networks:
            - knowy_net
        depends_on:
            -   postgres

    postgres:
        image: postgres:17
        container_name: kn-postgres17
        environment:
            POSTGRES_USER: knowy
            POSTGRES_PASSWORD: knowy
            POSTGRES_DB: knowydb
        ports:
            - "5434:5432"
        networks:
            - knowy_net
        volumes:
            - kn_db_data:/var/lib/postgresql/data
            - ./sql/init:/docker-entrypoint-initdb.d
    mailpit:
        container_name: kn-mailpit
        image: axllent/mailpit
        volumes:
            - kn_mailpit_data:/data
        ports:
            - 8025:8025 #UI mailpit port
            - 1025:1025 #SMTP port
        networks:
            - knowy_net
        environment:
            MP_MAX_MESSAGES: 1000
            MP_DATABASE: /data/knmailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
    kn_db_data:
    kn_mailpit_data:

networks:
    knowy_net: